# Generated by Django 3.0.2 on 2020-01-11 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('eventful_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000, null=True)),
                ('url', models.URLField(max_length=1000, null=True)),
                ('city', models.CharField(max_length=400, null=True)),
                ('country', models.CharField(max_length=400, null=True)),
                ('region', models.CharField(max_length=400, null=True)),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('eventful_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('url', models.URLField(max_length=500, null=True)),
                ('start_time', models.DateTimeField()),
                ('recur_string', models.CharField(max_length=500, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Venue')),
            ],
        ),
    ]
