# Generated by Django 3.0.2 on 2020-01-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('start_time', models.DateTimeField()),
            ],
        ),
    ]
